// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://keiruebwfgttprgkhgpz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtlaXJ1ZWJ3Zmd0dHByZ2toZ3B6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMDY0NzIsImV4cCI6MjA2ODU4MjQ3Mn0.iGS1rcOlm057_0hqZuZTeEfBO7VPukvvJNIe-x9LAiQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});